version: '3.7'
services:
  fc_mysqldb:
    container_name: micro-videos-mysqldbv2
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fc_catalogo_dev
    security_opt:
      - seccomp:unconfined
    ports:
      - 3307:3306
    networks:
      - fc_network

  adminer:
    container_name: micro-videos-adminerv2
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    networks:
      - fc_network
    depends_on:
      - fc_mysqldb

  app:
    container_name: micro-videos-appv2
    build:
      context: ./
      dockerfile: Dockerfile  
    volumes:
      - ./:/app
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 8005:8005
    networks:
      - fc_network
    depends_on:
      - fc_mysqldb
      
networks:
  fc_network:
